# Netlify configuration for Yacin Gym App
[build]
  publish = "dist"
  command = "npm run build-no-errors"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ':!README.md'"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  VITE_TEMPO = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Headers for performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://api.dicebear.com https://images.unsplash.com https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https: blob:; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https: wss:; media-src 'self' data: blob:; worker-src 'self' blob:;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    # Performance headers
    X-DNS-Prefetch-Control = "on"
    # PWA headers
    Service-Worker-Allowed = "/"

# Cache static assets with compression
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "gzip"
    Vary = "Accept-Encoding"

# Cache images
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Service Worker - Critical for offline functionality
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    Content-Type = "application/javascript"

# Manifest
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

# PWA headers
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Cache-Control = "no-cache"

# Audio files
[[headers]]
  for = "/*.mp3"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Gzip compression
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Offline fallback - Remove admin condition for public access
[[redirects]]
  from = "/offline"
  to = "/offline.html"
  status = 200

# Handle offline requests
[[redirects]]
  from = "/*"
  to = "/offline.html"
  status = 200
  conditions = {Role = ["offline"]}

# Build optimization - Enhanced for performance
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
  minify = true

[build.processing.images]
  compress = true
  quality = 85
  formats = ["webp", "avif"]

# Performance optimizations
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    output_path = "reports/lighthouse.html"
    
[[plugins]]
  package = "netlify-plugin-cache"
  
  [plugins.inputs.paths]
    node_modules = true
    dist = true

# Functions (if needed later)
[functions]
  directory = "netlify/functions"

# Edge functions (if needed later)
[edge_functions]
  directory = "netlify/edge-functions"

# Dev settings
[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  autoLaunch = false
  framework = "vite"

# Additional performance headers
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Link = "</assets/index.css>; rel=preload; as=style, </assets/index.js>; rel=preload; as=script"

# Preconnect to external domains
[[headers]]
  for = "/index.html"
  [headers.values]
    Link = "<https://api.dicebear.com>; rel=preconnect; crossorigin, <https://images.unsplash.com>; rel=preconnect; crossorigin, <https://fonts.googleapis.com>; rel=preconnect; crossorigin, <https://fonts.gstatic.com>; rel=preconnect; crossorigin"

# Error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404

# API routes (if needed in future)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Compression settings
[context.production]
  environment = { NODE_ENV = "production" }
  
[context.deploy-preview]
  environment = { NODE_ENV = "development" }
  
[context.branch-deploy]
  environment = { NODE_ENV = "development" }